### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by kk-delete** [Antu7/python-bruteForce#3]
Hey, i tried this attack on test account on https://vk.com and put password in passwords.txt, but it wrote this: "[!!] password not in list"
U write in code this string: print("[!!] password not in list"), so even if it is right password in .txt file, the program will write this.
Please, contact me in the near future

**Comment by Antu7** [comment]
It must be work I just try it myself. if it not then you must not follow the **read.me** file. Also, your provided website is down. Please read https://medium.com/@textmeantu/brute-force-attack-with-python-c1d70fcba607 link for a better understanding. Thank you.
